### ISSUE TITLE
Use CMake-Macro to retrieve sub-dir-list

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#577]
use for ```robotlist``` and ```envlist``` e.g. for install tags in various packages

See http://stackoverflow.com/questions/7787823/cmake-how-to-get-the-name-of-all-subdirectories-of-a-directory

as suggested by @ipa-mdl in https://github.com/ipa320/cob_robots/pull/573#discussion_r93017007

**Comment by mathias-luedtke** [comment]
File globbing might stop CMake from rebuilding as it does not detect changes..
I think we can export the (hand-crafted) robotlist from ` cob_hardware_config`.
In order to use it, we have to `build_depend` on `cob_hardware_config`.

In `cob_moveit_config` we should install files from the package directory with exclusion rules.

**Comment by fmessmer** [comment]
exported lists are used/proposed in all related packages....
