### ISSUE TITLE
dependencies to ur_driver / ur5_driver 

### ISSUE THREAD

**Issue by frederikhegger** [ipa320/cob_robots#80]
The "cob_bringup" package has a dependency to the package "ur_driver". I found the following repositories:
- https://github.com/ipa-nhg/ur_driver: here it seems that ur_driver would be a stack, but there is only one package inside (ur_description).
- https://kforge.ros.org/ros_industrial/universal_robot and https://github.com/ros-industrial/universal_robot: here there are only "ur5_*" packages. But in "./cob_bringup/components/ur10.launch" and "./cob_bringup/manifest.xml" it is refered to the  "ur_driver" package

So it seems that it is mixed up.

**Comment by fmessmer** [comment]
This issue has been fixed by the latest changes in cob_common and cob_robots for groovy!
See ipa320's groovy_dev branches of the respective stacks.

We are now using ur_driver and ur_description from here (https://github.com/ros-industrial/universal_robot). This stack has been updated recently as well.

However, we will not backport this to electric or fuerte.
